### ISSUE TITLE
Link to download PDF: Breaks if not on home/root page

### ISSUE THREAD

**Issue by CameronGray1210** [Seneca-ICTOER/Intro2C#163]
**Problem**: The link in the footer section to download the content PDF breaks most of the time as it only works if you are on the landing/index page.  

**Cause**: The link is relative to the active loaded page.

**Example**: 
1.	If I activate the page on “compilers” 
2.	The current URL becomes: /A-Introduction/compilers
3.	The download link for the PDF becomes: “/A-Introduction/Introduction-to-C.pdf”

This link needs to always point to the home/root page and not be relative to the current loaded page.

> NOTE
> A ***temporary fix*** has been applied that fully qualifies the URL path which is not desirable (especially in local builds/testing).

**Comment by Genne23v** [comment]
I think I can quickly fix this issue. Let me push my PR if it's ok.

**Comment by humphd** [comment]
@Genne23v great, go for it.
