### ISSUE TITLE
Generated PDF (GitHub Action): missing many images

### ISSUE THREAD

**Issue by CameronGray1210** [Seneca-ICTOER/Intro2C#168]
Generating the PDF on local machine will properly include all images, however, the automated PDF generation on GitHub fails to render many images.

**Comment by humphd** [comment]
Which one(s)?  cc @TueNguyen2911

**Comment by CameronGray1210** [comment]
Far too many to list (issue persists throughout all documents). It appears random and I don't see a pattern based on image type and syntax used in markdown - very perplexing.  Here are a few to references to get things started.  The generated PDF on GitHub misses the following images:

computer.md
- "Hardware": /img/programmer.png
- "Modern Computer": /img/hardware.png
- "Software": /img/software.png

information.md
- "Bytes": /img/bytenibbit.jpg
- "Memory Model": /img/ram.png
- "Addresses": /img/image21.png

Examples where images **DO render correctly**:

computers.md
- "Central Processing Unit": /img/cpu.png

compilers.md
- "Linux": /img/gcc.png
- "Windows": /img/cl.png

The interesting thing is when the PDF process is generated locally (on my machine anyway) it works fine.

**Comment by humphd** [comment]
This sounds like https://github.com/kohheepeace/mr-pdf/issues/37

**Comment by CameronGray1210** [comment]
Ahh.. yes that might very well be the cause.  I was able to replicate the missing images even on a local build.  When this happened, I then loaded all pages in the browser to build a cache, then generated the PDF and it worked.  So there seems to be a link to how it uses the cached images (or the slow loading of them) to the rendering in the PDF.

**Comment by humphd** [comment]
The fix for this is to have the render wait on all images to load fully.  I think it's likely to get fixed upstream.
