### ISSUE TITLE
Consider using Mermaid for Markdown diagrams

### ISSUE THREAD

**Issue by humphd** [Seneca-ICTOER/Intro2C#173]
[GitHub just added support](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/) for [Mermaid](http://mermaid-js.github.io/mermaid/#/) in their Markdown, and it looks really cool.  It's also [compatible with Docusaurus](https://www.npmjs.com/package/mdx-mermaid), see https://sjwall.github.io/mdx-mermaid/docs/intro/

A bunch of the diagrams in the C notes could be done with this vs. SVG or images, and they'd render much better.

**Comment by Genne23v** [comment]
I'm not sure if we can keep all original intention with `mermaid`, this is how it looks from my initial drafting. 
![Screen Shot 2022-11-11 at 9 38 20 AM](https://user-images.githubusercontent.com/59734889/201362680-9ae384c4-3b54-4832-bb56-a903038b6531.png)
Please let me know if I can go ahead with this on every page.

**Comment by humphd** [comment]
I wouldn't make this about doing "every page" but rather try doing it on a single page so we can evaluate the process.

CC'ing @CameronGray1210 for input.

**Comment by Genne23v** [comment]
Let me complete one page with my best styling efforts. Please review if this is a desired way.

**Comment by humphd** [comment]
Yes, doing a small sample on one page is the right approach.  Small, iterative changes are better than all-or-none.
